Repository gabymoreno9/alpha-works-website, pull requests merged in 2022-07, with the labels that each got.

#53 feat(izzy-btn): link btn to izzy's page
  index.html
  izzy/izzy-script.js
  izzy/izzy-style.css
  izzy/izzy.html
Labels: enhancement

#60 feat(Readme):Added Linkedin url
  README.md
Labels: documentation

#63 Doc(Client): add name and LinkedIn profile
  README.md
Labels: documentation

#66 feat(docs): add Linkedin link
  README.md
Labels: documentation

#69 ip-doc-README.md
  README.md
Labels: documentation

#79 feat(docs)Inserting full name and LinkedIn into README.md file
  README.md
Labels: documentation

#81 feat(jacky-css)added a big fix to the body background, instead of bod…
  jacky/jacky-styles.css
Labels: bug, enhancement

#84 feat(css-background) Fixing the bug for the background on the body fo…
  jacky/jacky-styles.css
Labels: bug

#85 Yg fs4 bio/hero
  yadi/yadi_img/code-world.png
  yadi/yadi_img/divider.png
  yadi/yadi_img/hero.png
  yadi/yadi_img/yadi-blackandwhite.png
  yadi/yadi_img/yg-logo-blue.png
  yadi/yadi_img/yg-logo.gif
  yadi/yadi_personal.html
  yadi/yadi_style.css
Labels: enhancement

#99 Feat(Client): Footer and Background
  Taofeek.html
  Taofeek/Taofeek.css
  Taofeek/Taofeek.html
  Taofeek/Taofeek.js
  Taofeek/footer.js
Labels: enhancement

#102 feat(navbar logo):changed bg color and added a new logo
  Eddie/Eddie.html
  Eddie/images/EM Logo (Lastica font) .png
  css/styles.css
Labels: enhancement

#105 Feat(Client):Create Navbar
  Taofeek/Taofeek.html
  Taofeek/Taofeek.js
Labels: enhancement

#110 feat(navbar): add navbar links
  izzy/izzy.html
Labels: enhancement

#123 fix(header):Fixed header and logo link
  Eddie/Eddie.html
  css/styles.css
Labels: bug

#161 feat(About me): Added an about me section with pic
  Eddie/Eddie.html
  Eddie/images/Eddie-Gray.JPG
  Eddie/images/EddieRedShirt[82].jpg
  Eddie/styles.css
  css/styles.css
Labels: enhancement

#164 feat(index) Fix bug on card to open at a separate tab
  index.html
Labels: bug, enhancement

#166 feat(new tab): Home button clicks to new tab
  index.html
Labels: enhancement

#168 feat(bug fix):fixed the homepage link to profile
  index.html
Labels: bug

#172 Feat(Client) T.A-171-Create top body
  Taofeek/Taofeek.html
  Taofeek/Taofeek.js
  Taofeek/img/Untitled.svg
Labels: enhancement

#183 feat(footer):added a footer with links
  Eddie/Eddie.html
  Eddie/styles.css
Labels: enhancement

#189 feat(footer links):Added links
  Eddie/Eddie.html
Labels: enhancement
